name: Master
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  create-executable:
    if: true
    name: Create executable
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: '${{ matrix.os }}'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: npm install
        run: npm ci
      - name: 'Create executable ${{ matrix.os }}'
        uses: ./.github/action
        with:
          task: create-executable
          os: '${{ matrix.os }}'
  draft-release:
    if: true
    name: Draft release
    needs: create-executable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: npm install
        run: npm ci
      - name: Draft release
        uses: ./.github/action
        with:
          task: draft-release
          githubToken: '${{ secrets.GITHUB_TOKEN }}'
