name: Master
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  check:
    if: false
    name: Check
    strategy:
      fail-fast: false
      matrix:
        command:
          - 'npm run check:depcheck'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: '${{ matrix.command }}'
        uses: ./.github/action
        with:
          command: '${{ matrix.command }}'
  build-packages:
    if: false
    name: Build packages
    strategy:
      fail-fast: false
      matrix:
        electronPlatform:
          - darwin
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build packages
        uses: ./.github/action
        with:
          task: build-packages
          electronPlatform: '${{ matrix.electronPlatform }}'
