name: Master
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  check:
    name: Check
    strategy:
      fail-fast: false
      matrix:
        command:
          - 'npm run check:lint'
          - 'npm run check:typescript'
          - 'npm run check:coverage'
          - 'npm run check:npm-audit'
          - 'npm run check:depcheck'
    runs-on: ubuntu-latest
    steps:
      - &ref_0
        name: Checkout repo
        uses: actions/checkout@v2
      - &ref_1
        name: npm install
        run: npm ci
      - name: '${{ matrix.command }}'
        uses: ./.github/action
        with:
          command: '${{ matrix.command }}'
  build-packages:
    if: true
    name: Build packages
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
    needs: check
    runs-on: '${{ matrix.os }}'
    steps:
      - *ref_0
      - *ref_1
      - name: 'Build package on ${{ matrix.os }}'
        uses: ./.github/action
        with:
          task: build-package
          os: '${{ matrix.os }}'
